// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniProject.Migrations;

#nullable disable

namespace MiniProject.Migrations.Migrations
{
    [DbContext(typeof(MiniDbContext))]
    [Migration("20261008124340_SeedPortfolioProfiles")]
    partial class SeedPortfolioProfiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniProject.Migrations.Entities.PortfolioExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "DisplayOrder");

                    b.ToTable("PortfolioExperiences", null, t =>
                        {
                            t.HasCheckConstraint("CK_PortfolioExperiences_CurrentHasNoEndDate", "[IsCurrent] = 0 OR [EndDate] IS NULL");

                            t.HasCheckConstraint("CK_PortfolioExperiences_DateRange", "[EndDate] IS NULL OR [EndDate] >= [StartDate]");

                            t.HasCheckConstraint("CK_PortfolioExperiences_DisplayOrder", "[DisplayOrder] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 201,
                            Company = "Northstar Labs",
                            Description = "Delivered customer-facing workflow tools, improved API observability, and worked with design and support to turn recurring customer issues into product improvements.",
                            DisplayOrder = 0,
                            EndDate = new DateOnly(2024, 1, 1),
                            IsCurrent = false,
                            JobTitle = "Software Engineer",
                            ProfileId = 1,
                            StartDate = new DateOnly(2022, 1, 1)
                        },
                        new
                        {
                            Id = 202,
                            Company = "Civic Works",
                            Description = "Built data visualization features and helped maintain open-source tools used by local research and community teams.",
                            DisplayOrder = 1,
                            EndDate = new DateOnly(2021, 12, 1),
                            IsCurrent = false,
                            JobTitle = "Software Developer",
                            ProfileId = 1,
                            StartDate = new DateOnly(2020, 6, 1)
                        },
                        new
                        {
                            Id = 203,
                            Company = "Brightside Studio",
                            Description = "Partnered with product designers to ship collaboration features, improve accessibility, and keep application performance predictable as usage grew.",
                            DisplayOrder = 0,
                            IsCurrent = true,
                            JobTitle = "Full-stack Developer",
                            ProfileId = 2,
                            StartDate = new DateOnly(2023, 7, 1)
                        },
                        new
                        {
                            Id = 204,
                            Company = "Cloudline",
                            Description = "Developed internal release tools and integrations, with an emphasis on reliable background processing and useful operational feedback.",
                            DisplayOrder = 1,
                            EndDate = new DateOnly(2023, 6, 1),
                            IsCurrent = false,
                            JobTitle = "Associate Developer",
                            ProfileId = 2,
                            StartDate = new DateOnly(2021, 8, 1)
                        });
                });

            modelBuilder.Entity("MiniProject.Migrations.Entities.PortfolioProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("Location")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ResumeUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.ToTable("PortfolioProfiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "I build reliable web products that make complex workflows easier to understand. My work spans API design, data modeling, and thoughtful frontend experiences.",
                            ContactEmail = "alex.rivera@example.com",
                            DisplayName = "Alex Rivera",
                            Headline = "Software Engineer | Data-rich web applications",
                            Location = "Seattle, WA",
                            ProfileImageUrl = "https://images.example.com/profiles/alex-rivera.jpg",
                            ResumeUrl = "https://example.com/resumes/alex-rivera.pdf"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "I turn early product ideas into maintainable software, from the first database schema to the polished interface. I enjoy making developer tools and collaborative products.",
                            ContactEmail = "maya.chen@example.com",
                            DisplayName = "Maya Chen",
                            Headline = "Full-stack Developer | Cloud and product engineering",
                            Location = "Toronto, ON",
                            ProfileImageUrl = "https://images.example.com/profiles/maya-chen.jpg",
                            ResumeUrl = "https://example.com/resumes/maya-chen.pdf"
                        });
                });

            modelBuilder.Entity("MiniProject.Migrations.Entities.PortfolioProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DemoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Description")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Organization")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "Slug")
                        .IsUnique();

                    b.HasIndex("ProfileId", "IsFeatured", "DisplayOrder");

                    b.ToTable("PortfolioProjects", null, t =>
                        {
                            t.HasCheckConstraint("CK_PortfolioProjects_DateRange", "[EndDate] IS NULL OR [StartDate] IS NULL OR [EndDate] >= [StartDate]");

                            t.HasCheckConstraint("CK_PortfolioProjects_DisplayOrder", "[DisplayOrder] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 101,
                            DemoUrl = "https://fieldnote.example.com",
                            Description = "Designed a workspace that brings meeting notes, decisions, and follow-up tasks together. Added full-text search, project timelines, and clear ownership so teams can recover context without digging through chat history.",
                            DisplayOrder = 0,
                            EndDate = new DateOnly(2024, 8, 1),
                            IsFeatured = true,
                            Organization = "Independent project",
                            ProfileId = 1,
                            Role = "Lead Engineer",
                            Slug = "fieldnote",
                            SourceUrl = "https://github.com/example/fieldnote",
                            StartDate = new DateOnly(2024, 2, 1),
                            Summary = "A searchable knowledge hub for teams working across customer projects.",
                            Title = "Fieldnote"
                        },
                        new
                        {
                            Id = 102,
                            Description = "Built a role-aware dashboard with saved filters, live status updates, and an audit trail. Optimized the API and database queries to keep large work queues responsive.",
                            DisplayOrder = 1,
                            EndDate = new DateOnly(2023, 12, 1),
                            IsFeatured = true,
                            Organization = "Northstar Labs",
                            ProfileId = 1,
                            Role = "Backend and UI Engineer",
                            Slug = "signal-board",
                            StartDate = new DateOnly(2023, 3, 1),
                            Summary = "An operations dashboard that turns incoming events into actionable queues.",
                            Title = "Signal Board"
                        },
                        new
                        {
                            Id = 103,
                            Description = "Created a responsive data catalog with reusable chart views, accessible controls, and shareable query URLs for researchers and community groups.",
                            DisplayOrder = 2,
                            EndDate = new DateOnly(2022, 11, 1),
                            IsFeatured = false,
                            Organization = "Civic Works",
                            ProfileId = 1,
                            Role = "Full-stack Engineer",
                            Slug = "open-data-explorer",
                            SourceUrl = "https://github.com/example/open-data-explorer",
                            StartDate = new DateOnly(2022, 4, 1),
                            Summary = "A lightweight way to browse, compare, and export public datasets.",
                            Title = "Open Data Explorer"
                        },
                        new
                        {
                            Id = 104,
                            DemoUrl = "https://studio-calendar.example.com",
                            Description = "Delivered shared availability, conflict detection, and approval flows with a mobile-first calendar. Added background reminders and clear permissions for members, guests, and administrators.",
                            DisplayOrder = 0,
                            EndDate = new DateOnly(2024, 10, 1),
                            IsFeatured = true,
                            Organization = "Brightside Studio",
                            ProfileId = 2,
                            Role = "Product Engineer",
                            Slug = "studio-calendar",
                            StartDate = new DateOnly(2024, 1, 1),
                            Summary = "A collaborative scheduling workspace for small creative studios.",
                            Title = "Studio Calendar"
                        },
                        new
                        {
                            Id = 105,
                            Description = "Integrated build events, deployment checks, and incident notes into one release timeline. Added retry-safe webhooks and notifications that link directly to the relevant change.",
                            DisplayOrder = 1,
                            EndDate = new DateOnly(2023, 11, 1),
                            IsFeatured = true,
                            Organization = "Cloudline",
                            ProfileId = 2,
                            Role = "Full-stack Developer",
                            Slug = "release-companion",
                            SourceUrl = "https://github.com/example/release-companion",
                            StartDate = new DateOnly(2023, 2, 1),
                            Summary = "A deployment companion that makes release status visible to every team.",
                            Title = "Release Companion"
                        },
                        new
                        {
                            Id = 106,
                            DemoUrl = "https://pantry-map.example.com",
                            Description = "Built an accessible map and contribution flow that lets local organizations keep resource details current. Focused on clear mobile navigation and simple moderation.",
                            DisplayOrder = 2,
                            EndDate = new DateOnly(2022, 12, 1),
                            IsFeatured = false,
                            Organization = "Neighbourhood Network",
                            ProfileId = 2,
                            Role = "Volunteer Developer",
                            Slug = "community-pantry-map",
                            StartDate = new DateOnly(2022, 5, 1),
                            Summary = "A volunteer-maintained map of food resources and opening hours.",
                            Title = "Community Pantry Map"
                        });
                });

            modelBuilder.Entity("MiniProject.Migrations.Entities.PortfolioSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "Name")
                        .IsUnique();

                    b.HasIndex("ProfileId", "Category", "DisplayOrder");

                    b.ToTable("PortfolioSkills", null, t =>
                        {
                            t.HasCheckConstraint("CK_PortfolioSkills_DisplayOrder", "[DisplayOrder] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 301,
                            Category = "Backend",
                            DisplayOrder = 0,
                            Name = "C#",
                            ProfileId = 1
                        },
                        new
                        {
                            Id = 302,
                            Category = "Backend",
                            DisplayOrder = 1,
                            Name = "ASP.NET Core",
                            ProfileId = 1
                        },
                        new
                        {
                            Id = 303,
                            Category = "Data",
                            DisplayOrder = 0,
                            Name = "SQL Server",
                            ProfileId = 1
                        },
                        new
                        {
                            Id = 304,
                            Category = "Frontend",
                            DisplayOrder = 0,
                            Name = "TypeScript",
                            ProfileId = 1
                        },
                        new
                        {
                            Id = 305,
                            Category = "Frontend",
                            DisplayOrder = 1,
                            Name = "React",
                            ProfileId = 1
                        },
                        new
                        {
                            Id = 306,
                            Category = "Cloud",
                            DisplayOrder = 0,
                            Name = "Azure",
                            ProfileId = 1
                        },
                        new
                        {
                            Id = 307,
                            Category = "Languages",
                            DisplayOrder = 0,
                            Name = "TypeScript",
                            ProfileId = 2
                        },
                        new
                        {
                            Id = 308,
                            Category = "Frontend",
                            DisplayOrder = 0,
                            Name = "React",
                            ProfileId = 2
                        },
                        new
                        {
                            Id = 309,
                            Category = "Backend",
                            DisplayOrder = 0,
                            Name = "Node.js",
                            ProfileId = 2
                        },
                        new
                        {
                            Id = 310,
                            Category = "Data",
                            DisplayOrder = 0,
                            Name = "PostgreSQL",
                            ProfileId = 2
                        },
                        new
                        {
                            Id = 311,
                            Category = "Cloud",
                            DisplayOrder = 0,
                            Name = "Docker",
                            ProfileId = 2
                        },
                        new
                        {
                            Id = 312,
                            Category = "Design",
                            DisplayOrder = 0,
                            Name = "Accessibility",
                            ProfileId = 2
                        });
                });

            modelBuilder.Entity("MiniProject.Migrations.Entities.PortfolioSocialLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "DisplayOrder");

                    b.HasIndex("ProfileId", "Label")
                        .IsUnique();

                    b.ToTable("PortfolioSocialLinks", null, t =>
                        {
                            t.HasCheckConstraint("CK_PortfolioSocialLinks_DisplayOrder", "[DisplayOrder] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 401,
                            DisplayOrder = 0,
                            Label = "GitHub",
                            ProfileId = 1,
                            Url = "https://github.com/alex-rivera"
                        },
                        new
                        {
                            Id = 402,
                            DisplayOrder = 1,
                            Label = "LinkedIn",
                            ProfileId = 1,
                            Url = "https://www.linkedin.com/in/alex-rivera"
                        },
                        new
                        {
                            Id = 403,
                            DisplayOrder = 2,
                            Label = "Website",
                            ProfileId = 1,
                            Url = "https://alex-rivera.example.com"
                        },
                        new
                        {
                            Id = 404,
                            DisplayOrder = 0,
                            Label = "GitHub",
                            ProfileId = 2,
                            Url = "https://github.com/maya-chen"
                        },
                        new
                        {
                            Id = 405,
                            DisplayOrder = 1,
                            Label = "LinkedIn",
                            ProfileId = 2,
                            Url = "https://www.linkedin.com/in/maya-chen"
                        },
                        new
                        {
                            Id = 406,
                            DisplayOrder = 2,
                            Label = "Website",
                            ProfileId = 2,
                            Url = "https://maya-chen.example.com"
                        });
                });

            modelBuilder.Entity("MiniProject.Migrations.Entities.ProjectSkill", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("ProjectSkills", (string)null);

                    b.HasData(
                        new
                        {
                            ProjectId = 101,
                            SkillId = 301
                        },
                        new
                        {
                            ProjectId = 101,
                            SkillId = 302
                        },
                        new
                        {
                            ProjectId = 101,
                            SkillId = 303
                        },
                        new
                        {
                            ProjectId = 101,
                            SkillId = 304
                        },
                        new
                        {
                            ProjectId = 101,
                            SkillId = 305
                        },
                        new
                        {
                            ProjectId = 102,
                            SkillId = 301
                        },
                        new
                        {
                            ProjectId = 102,
                            SkillId = 302
                        },
                        new
                        {
                            ProjectId = 102,
                            SkillId = 303
                        },
                        new
                        {
                            ProjectId = 102,
                            SkillId = 306
                        },
                        new
                        {
                            ProjectId = 103,
                            SkillId = 304
                        },
                        new
                        {
                            ProjectId = 103,
                            SkillId = 305
                        },
                        new
                        {
                            ProjectId = 103,
                            SkillId = 303
                        },
                        new
                        {
                            ProjectId = 104,
                            SkillId = 307
                        },
                        new
                        {
                            ProjectId = 104,
                            SkillId = 308
                        },
                        new
                        {
                            ProjectId = 104,
                            SkillId = 310
                        },
                        new
                        {
                            ProjectId = 104,
                            SkillId = 312
                        },
                        new
                        {
                            ProjectId = 105,
                            SkillId = 307
                        },
                        new
                        {
                            ProjectId = 105,
                            SkillId = 309
                        },
                        new
                        {
                            ProjectId = 105,
                            SkillId = 310
                        },
                        new
                        {
                            ProjectId = 105,
                            SkillId = 311
                        },
                        new
                        {
                            ProjectId = 106,
                            SkillId = 307
                        },
                        new
                        {
                            ProjectId = 106,
                            SkillId = 308
                        },
                        new
                        {
                            ProjectId = 106,
                            SkillId = 312
                        });
                });

            modelBuilder.Entity("MiniProject.Migrations.Entities.PortfolioExperience", b =>
                {
                    b.HasOne("MiniProject.Migrations.Entities.PortfolioProfile", "Profile")
                        .WithMany("Experiences")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("MiniProject.Migrations.Entities.PortfolioProject", b =>
                {
                    b.HasOne("MiniProject.Migrations.Entities.PortfolioProfile", "Profile")
                        .WithMany("Projects")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("MiniProject.Migrations.Entities.PortfolioSkill", b =>
                {
                    b.HasOne("MiniProject.Migrations.Entities.PortfolioProfile", "Profile")
                        .WithMany("Skills")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("MiniProject.Migrations.Entities.PortfolioSocialLink", b =>
                {
                    b.HasOne("MiniProject.Migrations.Entities.PortfolioProfile", "Profile")
                        .WithMany("SocialLinks")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("MiniProject.Migrations.Entities.ProjectSkill", b =>
                {
                    b.HasOne("MiniProject.Migrations.Entities.PortfolioProject", "Project")
                        .WithMany("ProjectSkills")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniProject.Migrations.Entities.PortfolioSkill", "Skill")
                        .WithMany("ProjectSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("MiniProject.Migrations.Entities.PortfolioProfile", b =>
                {
                    b.Navigation("Experiences");

                    b.Navigation("Projects");

                    b.Navigation("Skills");

                    b.Navigation("SocialLinks");
                });

            modelBuilder.Entity("MiniProject.Migrations.Entities.PortfolioProject", b =>
                {
                    b.Navigation("ProjectSkills");
                });

            modelBuilder.Entity("MiniProject.Migrations.Entities.PortfolioSkill", b =>
                {
                    b.Navigation("ProjectSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
