<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../MiniProject.ComplexLogicInMiddle/MiniProject.ComplexLogicInMiddle.csproj" />
    <ProjectReference Include="../MiniProject.Migrations/MiniProject.Migrations.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="wwwroot/**/*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
